import fs from 'fs';
import path from 'path';

// Current dist folder generated by vite build
const currentDist = path.resolve('dist');
const indexHtmlPath = path.join(currentDist, 'index.html');

if (fs.existsSync(indexHtmlPath)) {
  const htmlContent = fs.readFileSync(indexHtmlPath, 'utf-8');

  const routes = [
    'cuenta',
    'ropa',
    'calzado',
    'accesorios',
    'colecciones',
    'mas-vendidos',
    'ofertas',
    'admin',
    'carrito',
    'checkout',
    'nuevo',
    'favoritos'
  ];

  function populateFallbacks(targetDir) {
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }
    fs.writeFileSync(path.join(targetDir, '404.html'), htmlContent);
  }

  // 1. Populate current dist
  populateFallbacks(currentDist);

  // 2. Determine project root and populate root/dist, root/apps/web/dist, etc.
  let rootDir = process.cwd();
  if (fs.existsSync(path.join(rootDir, '..', 'apps', 'web'))) {
    rootDir = path.resolve(rootDir, '..');
  }

  const possibleDistLocations = [
    path.join(rootDir, 'dist'),
    path.join(rootDir, 'apps', 'web', 'dist'),
    path.join(rootDir, 'apps', 'web', 'apps', 'web', 'dist')
  ];

  possibleDistLocations.forEach((targetLoc) => {
    if (path.resolve(targetLoc) !== path.resolve(currentDist)) {
      try {
        fs.cpSync(currentDist, targetLoc, { recursive: true, force: true });
        populateFallbacks(targetLoc);
      } catch (err) {
        console.log(`Note: Non-fatal copy notice for ${targetLoc}:`, err.message);
      }
    }
  });

  console.log('=== TRIPLE-DIST POSTBUILD SUCCESS: Guaranteed Vercel deployment targets populated ===');
}
